### ISSUE TITLE
Suggestion: Auto Close "Alias Saved" green box after you've saved an alias

### ISSUE THREAD

**Issue by jklnz** [davidmckenzie/pagermon#44]
If that is possible?

**Comment by davidmckenzie** [comment]
Have pushed a change that does this now - in my testing it was a little unpredictable, probably due to the dodgy way I implemented the message displaying. Hopefully works alright though :)

**Comment by jklnz** [comment]
Hey @davidmckenzie - Just letting you know I dont think this worked, I still have the green box stay up after editing / adding Aliases

**Comment by davidmckenzie** [comment]
Huh weird... it's working on dev but not on prod for me.

**Comment by davidmckenzie** [comment]
Ok I see the issue - it fades once, but if you perform another action that generates a message without changing routes (i.e. click save, then click refresh aliases), then it doesn't fade.

**Comment by jklnz** [comment]
I was just going to write that I could get it to disappear sometimes, but not others - guess that explains it

**Comment by davidmckenzie** [comment]
Moved the timeout function out to the things that are actually triggering the alerts, that should do it. Only downside is the alerts don't fade away all pretty-like, but a worthy trade-off ;)

The code controlling those alerts is reaaaally messy. Need to pop it out to a function sometime soon.
